name: Deploy Apigee Proxy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: devapigeeproject-449204
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Authenticate with GCP
        run: |
          gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS

      - name: Deploy Apigee Proxy
        run: |
          gcloud apigee apis create hello-world --organization=devapigeeproject-449204 --source=./hello-world

      - name: Deploy Apigee API Proxy Revision
        run: |
          gcloud apigee apis deploy hello-world --organization=devapigeeproject-449204 --environment=eval

      - name: Verify Deployment
        run: |
          gcloud apigee deployments list --organization=devapigeeproject-449204
